# -*- coding: utf-8 -*-
"""Multimodal_Agentic_RAG_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114ZDLGB80A4KD0BtBRN3qkLhMYpS-ZjI

# Multi-Source Agentic RAG — Hybrid Retrieval + SQL + Web + Self-Correction

An agent that answers questions by routing across **hybrid document retrieval (BM25 + FAISS)**,
**SQL database queries**, and **live web search**, then **grades its own answer** against the
retrieved context and **retries with a rewritten query** if the answer isn't well-grounded.

Built entirely with LangChain Runnables (no LangGraph).

**Pipeline:** Ingestion → Splitting → Embeddings/Vectorstore → Hybrid Retriever → SQL Chain →
Web Search → Query Router → Dispatcher → Answer Generation → Self-Critique → Retry Loop →
Memory → Full Orchestration → Streamlit App

### 📦 Setup — install dependencies
"""

requirement=!pip install langchain-groq langchain-huggingface langchain-core langchain-community langchain-text-splitters langchain-classic rank-bm25 faiss-cpu duckduckgo-search streamlit python-dotenv pyngrok

"""### 🔧 Imports"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.output_parsers import StrOutputParser
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains import create_retrieval_chain, create_sql_query_chain
from langchain_core.documents import Document
import os
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader, CSVLoader
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_classic.retrievers import EnsembleRetriever, BM25Retriever
from langchain_community.utilities import SQLDatabase
from langchain_community.tools import DuckDuckGoSearchResults

load_dotenv()

"""## Step 1 — Document Loading
Loads raw documents from PDF, CSV, and DOCX files into LangChain `Document` objects.
Each loader function wraps the matching LangChain community loader.
"""

def load_pdf(file_path):
    """Load a PDF file and return a list of Document objects (one per page)."""
    loader = PyPDFLoader(file_path)
    return loader.load()

def load_csv(file_path):
    """Load a CSV file and return a list of Document objects (one per row)."""
    loader = CSVLoader(file_path)
    return loader.load()

def load_docx(file_path):
    """Load a DOCX file and return a list of Document objects."""
    loader = Docx2txtLoader(file_path)
    return loader.load()

def load_all_documents(pdf_paths=None, csv_paths=None, docx_paths=None):
    """Load and combine documents from any number of PDF/CSV/DOCX file paths."""
    all_documents = []
    for path in (pdf_paths or []):
        all_documents.extend(load_pdf(path))
    for path in (csv_paths or []):
        all_documents.extend(load_csv(path))
    for path in (docx_paths or []):
        all_documents.extend(load_docx(path))
    return all_documents

"""## Step 2 — Text Splitting
Breaks long documents into overlapping ~1000-character chunks so retrieval can return
focused, relevant passages instead of whole documents.
"""

def create_text_splitting(all_documents):
    """Split documents into overlapping chunks for retrieval."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    return splitter.split_documents(all_documents)

"""## Step 3 — Embeddings & Vector Store
Embeds chunks with a HuggingFace sentence-transformer model and stores them in a FAISS
vector index for fast similarity search. Also supports reloading a previously saved index.
"""

def create_embedding():
    """Create the embedding model used for both building and querying the vector store."""
    return HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

def create_vector_store(chunks, embeddings, save_path="faiss_index"):
    """Build a FAISS vector store from chunks and persist it to disk."""
    vectorstore = FAISS.from_documents(documents=chunks, embedding=embeddings)
    vectorstore.save_local(save_path)
    return vectorstore

def load_vector_store(embeddings, save_path="faiss_index"):
    """Reload a previously saved FAISS vector store from disk."""
    return FAISS.load_local(save_path, embeddings, allow_dangerous_deserialization=True)

"""## Step 4-5 — Semantic Retriever & BM25 Retriever
Two independent retrieval strategies: a semantic (embedding-based) retriever for meaning/paraphrase
matches, and a BM25 keyword retriever for exact-term matches (IDs, names, jargon).
"""

def create_semantic_retriever(vectorstore, k=3):
    """Similarity-based retriever backed by the FAISS vector store."""
    return vectorstore.as_retriever(search_type="mmr", search_kwargs={"k": k})

def create_bm25_retriever(chunks, k=3):
    """Keyword-based retriever using BM25 ranking over the same chunks."""
    bm25 = BM25Retriever.from_documents(chunks)
    bm25.k = k
    return bm25

"""## Step 6 — Hybrid Retriever
Combines the semantic and BM25 retrievers with `EnsembleRetriever`, which merges their
ranked results (reciprocal rank fusion) so you get both keyword precision and semantic recall.
"""

def create_hybrid_retriever(semantic_retriever, bm25_retriever, weights=(0.5, 0.5)):
    """Merge semantic + BM25 retrievers into one hybrid retriever."""
    return EnsembleRetriever(
        retrievers=[semantic_retriever, bm25_retriever],
        weights=list(weights)
    )

"""## Step 7 — SQL Retriever
Connects to a SQLite database, turns a natural-language question into a SQL query with
`create_sql_query_chain`, then **executes** that query against the database to get real rows back
(the raw chain only generates SQL text — `run_sql_query` is what actually fetches data).
"""

def load_database(db_path="company.db"):
    """Connect to a SQLite database file for structured/tabular queries."""
    return SQLDatabase.from_uri(f"sqlite:///{db_path}")

def create_sql_chain(llm, db):
    """Chain that turns a natural-language question into a SQL query string."""
    return create_sql_query_chain(llm, db)

def run_sql_query(question, sql_chain, db):
    """Generate SQL for the question and execute it against the database, returning real results."""
    sql_query = sql_chain.invoke({"question": question})
    try:
        result = db.run(sql_query)
    except Exception as e:
        result = f"SQL execution failed: {e}"
    return sql_query, result

"""## Step 7b — Web Search Tool
Wraps DuckDuckGo search so the agent can answer questions about current events or anything
not likely to be in the local documents or database.
"""

def create_web_search_tool():
    """Create the DuckDuckGo web search tool."""
    return DuckDuckGoSearchResults()

def run_web_search(query, search_tool):
    """Run a live web search and return the results as text."""
    try:
        return search_tool.invoke(query)
    except Exception as e:
        return f"Web search failed: {e}"

"""## Step 8 — Query Router
An LLM classifier that decides, per question, whether to use the hybrid document retriever,
the SQL database, or live web search. This avoids brittle keyword-based routing.
"""

def create_query_router(llm):
    """LLM-based router that classifies a question into hybrid / sql / web."""
    prompt = ChatPromptTemplate.from_template(
        """
You are a query routing assistant.

Your job is to decide which data source should answer the user's question.

Available data sources:

1. hybrid
- Questions about PDFs, DOCX, CSV files
- General knowledge stored in the local vector database
- Research documents

2. sql
- Questions about structured employee/company data
- Salary, Department, Experience, Employee IDs, Database records

3. web
- Latest news, current events, live information
- Information not likely to exist in local documents

Return ONLY one word: hybrid, sql, or web. No punctuation, no explanation.

Question:
{question}
"""
    )
    return prompt | llm | StrOutputParser()

def route_query(query, router):
    """Classify a query into 'hybrid', 'sql', or 'web'."""
    source = router.invoke({"question": query}).strip().lower()
    if source not in ("hybrid", "sql", "web"):
        source = "hybrid"  # safe fallback if the LLM returns something unexpected
    return source

"""## Step 8b — Dispatcher (execute_route)
Runs the actual retrieval/query/search for whichever source the router picked, and returns
both the raw result and a single formatted context string ready for the answer prompt.
Falls back gracefully to the hybrid retriever if SQL is chosen but no database is connected.
"""

def format_context(source, raw_result):
    """Turn the raw result from any source into a single context string for the LLM."""
    if source == "hybrid":
        return "\n\n".join(doc.page_content for doc in raw_result)
    return str(raw_result)

def execute_route(source, query, hybrid_retriever, sql_chain, db, search_tool):
    """Run the retrieval/query/search matching the routed source.

    Returns: (source_used, raw_result, context_text)
    """
    if source == "hybrid":
        docs = hybrid_retriever.invoke(query)
        return "hybrid", docs, format_context("hybrid", docs)

    elif source == "sql":
        if db is None or sql_chain is None:
            # No database connected -- fall back to documents instead of crashing
            docs = hybrid_retriever.invoke(query)
            return "hybrid (sql unavailable)", docs, format_context("hybrid", docs)
        sql_query, result = run_sql_query(query, sql_chain, db)
        context = f"SQL Query: {sql_query}\nResult: {result}"
        return "sql", result, context

    elif source == "web":
        result = run_web_search(query, search_tool)
        return "web", result, format_context("web", result)

    else:
        raise ValueError(f"Unknown source: {source}")

"""## Step 9-10 — Answer Generation
Generates the final answer strictly from the retrieved context (with recent chat history for
continuity), and instructs the model to say so honestly when the context doesn't contain
the answer rather than guessing.
"""

def create_answer_prompt():
    """Prompt template for grounded answer generation."""
    return ChatPromptTemplate.from_template(
        """
You are an AI Research Assistant.

Answer the user's question ONLY using the provided context.
If the answer is not in the context, say:
"I don't have enough information to answer this."

Conversation History:
{chat_history}

Context:
{context}

Question:
{question}
"""
    )

def create_answer_chain(llm):
    """Runnable chain: prompt -> llm -> plain text answer."""
    prompt = create_answer_prompt()
    return prompt | llm | StrOutputParser()

def generate_answer(question, context, chat_history, answer_chain):
    """Generate a grounded answer given a question, context, and prior chat history."""
    return answer_chain.invoke({
        "question": question,
        "context": context,
        "chat_history": chat_history
    })

"""## Step 12 — Self-Critique
A second LLM call grades the generated answer against the retrieved context, returning PASS
if the answer is fully supported, or FAIL if it looks hallucinated or ungrounded. This is what
lets the agent catch its own bad answers instead of confidently returning them.
"""

def create_critique_prompt():
    """Prompt template for grading an answer against its context."""
    return ChatPromptTemplate.from_template(
        """You are an AI evaluator.

Evaluate whether the answer is supported by the provided context.

Context:
{context}

Question:
{question}

Answer:
{answer}

Return ONLY one word.

PASS -> if the answer is fully supported.
FAIL -> if the answer is incorrect, hallucinated, or not supported by the context.
"""
    )

def create_critique_chain(llm):
    """Runnable chain: prompt -> llm -> PASS/FAIL verdict."""
    prompt = create_critique_prompt()
    return prompt | llm | StrOutputParser()

def evaluate_answer(question, context, answer, critique_chain):
    """Grade an answer against its context, returning 'pass' or 'fail'."""
    verdict = critique_chain.invoke({
        "question": question,
        "context": context,
        "answer": answer
    })
    return verdict.strip().lower()

"""## Step 13 — Retry Loop (Self-Correction)
If the critique returns FAIL, an LLM rewrites the question to be clearer/more specific, then the
whole route -> retrieve -> answer -> critique cycle runs again, up to `max_retries` times.
This is the hand-rolled reflection loop -- built with plain Runnables, no LangGraph.
"""

def create_rewrite_chain(llm):
    """Chain that rewrites a question that failed self-critique, to retrieve better context."""
    prompt = ChatPromptTemplate.from_template(
        """
The following question did not receive a well-supported answer from the retrieved context.
Rewrite it to be clearer and more specific so retrieval is more likely to find relevant information.
Return ONLY the rewritten question, nothing else.

Original Question:
{question}
"""
    )
    return prompt | llm | StrOutputParser()

def answer_with_self_correction(
    query,
    chat_history,
    router,
    hybrid_retriever,
    sql_chain,
    db,
    search_tool,
    answer_chain,
    critique_chain,
    rewrite_chain,
    max_retries=2
):
    """Full route -> answer -> critique -> retry cycle for a single question."""
    current_query = query
    attempts = []
    source_used, context_text, answer = None, "", ""

    for attempt in range(max_retries + 1):
        source_used = route_query(current_query, router)
        _, _, context_text = execute_route(source_used, current_query, hybrid_retriever, sql_chain, db, search_tool)
        answer = generate_answer(current_query, context_text, chat_history, answer_chain)
        verdict = evaluate_answer(current_query, context_text, answer, critique_chain)

        attempts.append({"attempt": attempt + 1, "query": current_query, "source": source_used, "verdict": verdict})

        if verdict == "pass":
            return {"answer": answer, "source": source_used, "context": context_text,
                    "attempts": attempts, "grounded": True}

        if attempt < max_retries:
            current_query = rewrite_chain.invoke({"question": current_query}).strip()

    return {"answer": answer, "source": source_used, "context": context_text,
            "attempts": attempts, "grounded": False}

"""## Step 14 — Memory
Keeps a per-session chat history so follow-up questions have conversational context. The history
is stored in-memory per `session_id` and passed into the answer prompt on every turn.
"""

_session_store = {}

def get_session_history(session_id: str):
    """Get (or create) the chat history for a session id."""
    if session_id not in _session_store:
        _session_store[session_id] = InMemoryChatMessageHistory()
    return _session_store[session_id]

def format_chat_history(history, max_turns=5):
    """Render the last few turns of chat history as plain text for the prompt."""
    messages = history.messages[-(max_turns * 2):]
    lines = []
    for m in messages:
        role = "User" if m.type == "human" else "Assistant"
        lines.append(f"{role}: {m.content}")
    return "\n".join(lines) if lines else "(no previous conversation)"

def clear_session(session_id: str):
    """Clear the chat history for a session id."""
    if session_id in _session_store:
        del _session_store[session_id]

"""## Step 15 — Full Orchestration
`initialize_pipeline` builds every component once (LLM, vectorstore, retrievers, chains).
`run_agent` is the single entry point the app calls per user turn: it pulls session memory,
runs the self-correcting answer loop, then saves the turn back to memory.
"""

def initialize_pipeline(pdf_paths=None, csv_paths=None, docx_paths=None, db_path=None, groq_api_key=None):
    """Build every pipeline component once and return them in a single dict."""
    api_key = groq_api_key or os.getenv("GROQ_API_KEY")
    llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.3, api_key=api_key)

    all_documents = load_all_documents(pdf_paths, csv_paths, docx_paths)
    chunks = create_text_splitting(all_documents)

    embeddings = create_embedding()
    vectorstore = create_vector_store(chunks, embeddings)

    semantic_retriever = create_semantic_retriever(vectorstore)
    bm25_retriever = create_bm25_retriever(chunks)
    hybrid_retriever = create_hybrid_retriever(semantic_retriever, bm25_retriever)

    db, sql_chain = None, None
    if db_path and os.path.exists(db_path):
        db = load_database(db_path)
        sql_chain = create_sql_chain(llm, db)

    search_tool = create_web_search_tool()

    router = create_query_router(llm)
    answer_chain = create_answer_chain(llm)
    critique_chain = create_critique_chain(llm)
    rewrite_chain = create_rewrite_chain(llm)

    return {
        "llm": llm,
        "chunk_count": len(chunks),
        "doc_count": len(all_documents),
        "hybrid_retriever": hybrid_retriever,
        "sql_chain": sql_chain,
        "db": db,
        "search_tool": search_tool,
        "router": router,
        "answer_chain": answer_chain,
        "critique_chain": critique_chain,
        "rewrite_chain": rewrite_chain,
    }

def run_agent(query, session_id, pipeline, max_retries=2):
    """Single entry point: answer one user turn with memory + self-correction."""
    history = get_session_history(session_id)
    chat_history_text = format_chat_history(history)

    result = answer_with_self_correction(
        query=query,
        chat_history=chat_history_text,
        router=pipeline["router"],
        hybrid_retriever=pipeline["hybrid_retriever"],
        sql_chain=pipeline["sql_chain"],
        db=pipeline["db"],
        search_tool=pipeline["search_tool"],
        answer_chain=pipeline["answer_chain"],
        critique_chain=pipeline["critique_chain"],
        rewrite_chain=pipeline["rewrite_chain"],
        max_retries=max_retries
    )

    history.add_user_message(query)
    history.add_ai_message(result["answer"])
    return result

"""## Quick test (optional)
Run this once you have `sample.pdf` / `sample.csv` / `sample.docx` (and optionally `company.db`)
in the working directory to sanity-check the full pipeline before moving to the Streamlit app.
"""

# pipeline = initialize_pipeline(
#     pdf_paths=["sample.pdf"], csv_paths=["sample.csv"], docx_paths=["sample.docx"],
#     db_path="company.db"
# )
# result = run_agent("What does the document say about the project timeline?", "test_session", pipeline)
# print(result["answer"])
# print("Source used:", result["source"], "| Grounded:", result["grounded"])
# print("Attempts:", result["attempts"])

"""## Streamlit App
Writes `app.py` to disk. Upload PDFs/CSVs/DOCX (and optionally a SQLite `.db` file) in the
sidebar, click **Process Documents**, then chat. Each answer shows which source was used
and whether it passed self-critique on the first try or needed a retry.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# import tempfile
# from dotenv import load_dotenv
# 
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_community.vectorstores import FAISS
# from langchain_groq import ChatGroq
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_core.output_parsers import StrOutputParser
# from langchain_classic.chains import create_sql_query_chain
# from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader, CSVLoader
# from langchain_core.chat_history import InMemoryChatMessageHistory
# from langchain_classic.retrievers import EnsembleRetriever, BM25Retriever
# from langchain_community.utilities import SQLDatabase
# from langchain_community.tools import DuckDuckGoSearchResults
# 
# load_dotenv()
# 
# # ---------------- Pipeline functions ----------------
# 
# def load_pdf(p):
#     return PyPDFLoader(p).load()
# 
# def load_csv(p):
#     return CSVLoader(p).load()
# 
# def load_docx(p):
#     return Docx2txtLoader(p).load()
# 
# def save_upload_file(uploaded_file):
#     os.makedirs("temp", exist_ok=True)
#     temp_path = os.path.join("temp", uploaded_file.name)
#     with open(temp_path, "wb") as f:
#         f.write(uploaded_file.getbuffer())
#     return temp_path
# 
# def create_text_splitting(docs):
#     splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200, length_function=len)
#     return splitter.split_documents(docs)
# 
# def create_embedding():
#     return HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
# 
# def create_vector_store(chunks, embeddings):
#     vs = FAISS.from_documents(documents=chunks, embedding=embeddings)
#     vs.save_local("faiss_index")
#     return vs
# 
# def create_semantic_retriever(vectorstore, k=3):
#     return vectorstore.as_retriever(search_type="mmr", search_kwargs={"k": k})
# 
# def create_bm25_retriever(chunks, k=3):
#     bm25 = BM25Retriever.from_documents(chunks)
#     bm25.k = k
#     return bm25
# 
# def create_hybrid_retriever(semantic_retriever, bm25_retriever, weights=(0.5, 0.5)):
#     return EnsembleRetriever(retrievers=[semantic_retriever, bm25_retriever], weights=list(weights))
# 
# def load_database(db_path):
#     return SQLDatabase.from_uri(f"sqlite:///{db_path}")
# 
# def create_sql_chain(llm, db):
#     return create_sql_query_chain(llm, db)
# 
# def run_sql_query(question, sql_chain, db):
#     sql_query = sql_chain.invoke({"question": question})
#     try:
#         result = db.run(sql_query)
#     except Exception as e:
#         result = f"SQL execution failed: {e}"
#     return sql_query, result
# 
# def create_web_search_tool():
#     return DuckDuckGoSearchResults()
# 
# def run_web_search(query, search_tool):
#     try:
#         return search_tool.invoke(query)
#     except Exception as e:
#         return f"Web search failed: {e}"
# 
# def create_query_router(llm):
#     prompt = ChatPromptTemplate.from_template(
#         """
# You are a query routing assistant.
# Decide which data source should answer the user's question.
# 
# 1. hybrid - Questions about PDFs, DOCX, CSV files, research documents, general local knowledge
# 2. sql - Structured employee/company data: salary, department, experience, employee IDs, records
# 3. web - Latest news, current events, live information not likely in local documents
# 
# Return ONLY one word: hybrid, sql, or web.
# 
# Question:
# {question}
# """
#     )
#     return prompt | llm | StrOutputParser()
# 
# def route_query(query, router):
#     source = router.invoke({"question": query}).strip().lower()
#     if source not in ("hybrid", "sql", "web"):
#         source = "hybrid"
#     return source
# 
# def format_context(source, raw_result):
#     if source == "hybrid":
#         return "\n\n".join(doc.page_content for doc in raw_result)
#     return str(raw_result)
# 
# def execute_route(source, query, hybrid_retriever, sql_chain, db, search_tool):
#     if source == "hybrid":
#         docs = hybrid_retriever.invoke(query)
#         return "hybrid", docs, format_context("hybrid", docs)
#     elif source == "sql":
#         if db is None or sql_chain is None:
#             docs = hybrid_retriever.invoke(query)
#             return "hybrid (sql unavailable)", docs, format_context("hybrid", docs)
#         sql_query, result = run_sql_query(query, sql_chain, db)
#         return "sql", result, f"SQL Query: {sql_query}\nResult: {result}"
#     elif source == "web":
#         result = run_web_search(query, search_tool)
#         return "web", result, format_context("web", result)
#     else:
#         raise ValueError(f"Unknown source: {source}")
# 
# def create_answer_chain(llm):
#     prompt = ChatPromptTemplate.from_template(
#         """
# You are an AI Research Assistant.
# Answer the user's question ONLY using the provided context.
# If the answer is not in the context, say: "I don't have enough information to answer this."
# 
# Conversation History:
# {chat_history}
# 
# Context:
# {context}
# 
# Question:
# {question}
# """
#     )
#     return prompt | llm | StrOutputParser()
# 
# def generate_answer(question, context, chat_history, answer_chain):
#     return answer_chain.invoke({"question": question, "context": context, "chat_history": chat_history})
# 
# def create_critique_chain(llm):
#     prompt = ChatPromptTemplate.from_template(
#         """You are an AI evaluator. Evaluate whether the answer is supported by the provided context.
# 
# Context:
# {context}
# 
# Question:
# {question}
# 
# Answer:
# {answer}
# 
# Return ONLY one word.
# PASS -> if the answer is fully supported.
# FAIL -> if the answer is incorrect, hallucinated, or not supported by the context.
# """
#     )
#     return prompt | llm | StrOutputParser()
# 
# def evaluate_answer(question, context, answer, critique_chain):
#     verdict = critique_chain.invoke({"question": question, "context": context, "answer": answer})
#     return verdict.strip().lower()
# 
# def create_rewrite_chain(llm):
#     prompt = ChatPromptTemplate.from_template(
#         """
# The following question did not receive a well-supported answer from the retrieved context.
# Rewrite it to be clearer and more specific. Return ONLY the rewritten question.
# 
# Original Question:
# {question}
# """
#     )
#     return prompt | llm | StrOutputParser()
# 
# def answer_with_self_correction(query, chat_history, router, hybrid_retriever, sql_chain, db,
#                                  search_tool, answer_chain, critique_chain, rewrite_chain, max_retries=2):
#     current_query = query
#     attempts = []
#     source_used, context_text, answer = None, "", ""
# 
#     for attempt in range(max_retries + 1):
#         source_used = route_query(current_query, router)
#         _, _, context_text = execute_route(source_used, current_query, hybrid_retriever, sql_chain, db, search_tool)
#         answer = generate_answer(current_query, context_text, chat_history, answer_chain)
#         verdict = evaluate_answer(current_query, context_text, answer, critique_chain)
#         attempts.append({"attempt": attempt + 1, "query": current_query, "source": source_used, "verdict": verdict})
# 
#         if verdict == "pass":
#             return {"answer": answer, "source": source_used, "context": context_text,
#                     "attempts": attempts, "grounded": True}
#         if attempt < max_retries:
#             current_query = rewrite_chain.invoke({"question": current_query}).strip()
# 
#     return {"answer": answer, "source": source_used, "context": context_text,
#             "attempts": attempts, "grounded": False}
# 
# def get_session_history(session_id):
#     if session_id not in st.session_state.history_store:
#         st.session_state.history_store[session_id] = InMemoryChatMessageHistory()
#     return st.session_state.history_store[session_id]
# 
# def format_chat_history(history, max_turns=5):
#     messages = history.messages[-(max_turns * 2):]
#     lines = [f"{'User' if m.type == 'human' else 'Assistant'}: {m.content}" for m in messages]
#     return "\n".join(lines) if lines else "(no previous conversation)"
# 
# def initialize_pipeline(pdf_paths, csv_paths, docx_paths, db_path):
#     api_key = os.getenv("GROQ_API_KEY")
#     llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.3, api_key=api_key)
# 
#     all_documents = []
#     for p in pdf_paths:
#         all_documents.extend(load_pdf(p))
#     for p in csv_paths:
#         all_documents.extend(load_csv(p))
#     for p in docx_paths:
#         all_documents.extend(load_docx(p))
# 
#     chunks = create_text_splitting(all_documents)
#     embeddings = create_embedding()
#     vectorstore = create_vector_store(chunks, embeddings)
# 
#     semantic_retriever = create_semantic_retriever(vectorstore)
#     bm25_retriever = create_bm25_retriever(chunks)
#     hybrid_retriever = create_hybrid_retriever(semantic_retriever, bm25_retriever)
# 
#     db, sql_chain = None, None
#     if db_path and os.path.exists(db_path):
#         db = load_database(db_path)
#         sql_chain = create_sql_chain(llm, db)
# 
#     search_tool = create_web_search_tool()
#     router = create_query_router(llm)
#     answer_chain = create_answer_chain(llm)
#     critique_chain = create_critique_chain(llm)
#     rewrite_chain = create_rewrite_chain(llm)
# 
#     return {
#         "doc_count": len(all_documents), "chunk_count": len(chunks),
#         "hybrid_retriever": hybrid_retriever, "sql_chain": sql_chain, "db": db,
#         "search_tool": search_tool, "router": router, "answer_chain": answer_chain,
#         "critique_chain": critique_chain, "rewrite_chain": rewrite_chain,
#     }
# 
# def run_agent(query, session_id, pipeline, max_retries=2):
#     history = get_session_history(session_id)
#     chat_history_text = format_chat_history(history)
#     result = answer_with_self_correction(
#         query=query, chat_history=chat_history_text, router=pipeline["router"],
#         hybrid_retriever=pipeline["hybrid_retriever"], sql_chain=pipeline["sql_chain"],
#         db=pipeline["db"], search_tool=pipeline["search_tool"], answer_chain=pipeline["answer_chain"],
#         critique_chain=pipeline["critique_chain"], rewrite_chain=pipeline["rewrite_chain"],
#         max_retries=max_retries
#     )
#     history.add_user_message(query)
#     history.add_ai_message(result["answer"])
#     return result
# 
# # ---------------- Streamlit UI ----------------
# 
# def main():
#     st.set_page_config(page_title="Agentic Multi-Source RAG", page_icon="\U0001F9E0", layout="wide")
#     st.title("\U0001F9E0 Agentic Multi-Source RAG")
#     st.caption("Hybrid retrieval (BM25 + FAISS) - SQL - Web search - Self-critique - Retry loop - Memory")
# 
#     if not os.getenv("GROQ_API_KEY"):
#         st.warning("GROQ_API_KEY is not set. Add it to your .env file before processing documents.")
# 
#     if "messages" not in st.session_state:
#         st.session_state.messages = []
#     if "history_store" not in st.session_state:
#         st.session_state.history_store = {}
#     if "pipeline" not in st.session_state:
#         st.session_state.pipeline = None
# 
#     with st.sidebar:
#         st.subheader("1. Upload sources")
#         pdf_files = st.file_uploader("PDF documents", type=["pdf"], accept_multiple_files=True)
#         csv_files = st.file_uploader("CSV documents", type=["csv"], accept_multiple_files=True)
#         docx_files = st.file_uploader("DOCX documents", type=["docx"], accept_multiple_files=True)
#         db_file = st.file_uploader("SQLite database (optional)", type=["db"])
# 
#         process = st.button("\U0001F680 Process Documents")
# 
#         st.divider()
#         max_retries = st.slider("Max self-correction retries", 0, 3, 2)
# 
#         if st.button("\U0001F5D1\uFE0F Clear chat"):
#             st.session_state.messages = []
#             st.session_state.history_store = {}
#             st.rerun()
# 
#     if process:
#         if not (pdf_files or csv_files or docx_files):
#             st.warning("Please upload at least one PDF, CSV, or DOCX document to process.")
#         else:
#             with st.spinner("Processing documents and building the pipeline..."):
#                 pdf_paths = [save_upload_file(f) for f in (pdf_files or [])]
#                 csv_paths = [save_upload_file(f) for f in (csv_files or [])]
#                 docx_paths = [save_upload_file(f) for f in (docx_files or [])]
#                 db_path = save_upload_file(db_file) if db_file else None
# 
#                 st.session_state.pipeline = initialize_pipeline(pdf_paths, csv_paths, docx_paths, db_path)
#             st.success(
#                 f"Processed {st.session_state.pipeline['doc_count']} documents "
#                 f"into {st.session_state.pipeline['chunk_count']} chunks."
#             )
# 
#     if st.session_state.pipeline:
#         for message in st.session_state.messages:
#             with st.chat_message(message["role"]):
#                 st.markdown(message["content"])
#                 if message.get("meta"):
#                     st.caption(message["meta"])
# 
#         query = st.chat_input("Ask a question...")
#         if query:
#             st.session_state.messages.append({"role": "user", "content": query})
#             with st.chat_message("user"):
#                 st.markdown(query)
# 
#             try:
#                 with st.spinner("Thinking..."):
#                     result = run_agent(query, "user1", st.session_state.pipeline, max_retries=max_retries)
# 
#                 retries_used = len(result["attempts"]) - 1
#                 grounded_label = "\u2705 grounded" if result["grounded"] else "\u26A0\uFE0F not fully grounded after retries"
#                 meta = f"Source: {result['source']} | Retries: {retries_used} | {grounded_label}"
# 
#                 with st.chat_message("assistant"):
#                     st.markdown(result["answer"])
#                     st.caption(meta)
#                     with st.expander("View retrieved context / attempts"):
#                         st.write(result["context"])
#                         st.json(result["attempts"])
# 
#                 st.session_state.messages.append({"role": "assistant", "content": result["answer"], "meta": meta})
# 
#             except Exception as e:
#                 st.error(f"Error: {e}")
#     else:
#         st.info("Upload documents in the sidebar and click **Process Documents** to start chatting.")
# 
# if __name__ == "__main__":
#     main()
#

"""### Running the app from Colab
```
!streamlit run app.py &>/content/logs.txt &
from pyngrok import ngrok
public_url = ngrok.connect(8501)
public_url
```
Or, if running locally instead of Colab, just run `streamlit run app.py` from a terminal in this folder.

"""